name: Android CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: 'zulu'

    # Set up Android SDK
    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: 35
        build-tools: 35.0.0

    # Grant Gradle permissions
    - name: Grant execute permission for Gradle wrapper
      run: chmod +x gradlew

    # Install dependencies and build
    - name: Build the project
      run: ./gradlew assembleDebug

    # Run unit tests
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest

    # Run instrumented tests
    - name: Run instrumented tests
      run: ./gradlew connectedDebugAndroidTest
